import { NetworkGatewayGuard } from '../mocks/networkMock';


export interface PolicyConfig {
  allowedPaths?: string[];     // Directories the agent is allowed to touch
  blockedCommands?: string[];   // Specific binary names to blacklist completely
  allowInternet?: boolean;      // Future-proofing flag for network gateway mocking
  maxCommandLength?: number;    // Protect against buffer/memory straining payloads
}

export interface ValidationResult {
  isSafe: boolean;
  reason?: string;
  sanitizedCommand?: string;
}

export class SecurityPolicy {
  private allowedPaths: string[];
  private blockedCommands: string[];
  private allowInternet: boolean;
  private maxCommandLength: number;

  constructor(config: PolicyConfig = {}) {
    // Default safe profiles if the developer doesn't supply constraints
    this.allowedPaths = config.allowedPaths || [];
    this.blockedCommands = config.blockedCommands || [
      'sudo', 'su', 'rm', 'mv', 'dd', 'mkfs', 'chown', 'chmod', 'passwd', 'kill', 'pkill'
    ];
    this.allowInternet = config.allowInternet !== undefined ? config.allowInternet : false;
    this.maxCommandLength = config.maxCommandLength || 1000;
  }

  /**
   * Evaluates a raw CLI string generated by an autonomous AI agent.
   */
  public validate(rawCommand: string): ValidationResult {
    const trimmed = rawCommand.trim();

    // 1. Structural Check: Empty string payload
    if (!trimmed) {
      return { isSafe: false, reason: "Command is empty" };
    }

    // 2. Length Constraint Validation
    if (trimmed.length > this.maxCommandLength) {
      return { 
        isSafe: false, 
        reason: `Command exceeds maximum safety length limit of ${this.maxCommandLength} characters.` 
      };
    }

    // 3. Command Injection & Pipeline Splitting Analysis
    // We break the execution down by shell operators (&&, ||, ;, |) to evaluate each segment independently
    const segments = trimmed.split(/[&|;]/);
    
    for (const segment of segments) {
      const cleanSegment = segment.trim();
      if (!cleanSegment) continue;

      // Extract the primary executable/binary token (e.g., "rm" out of "rm -rf /")
      const tokens = cleanSegment.split(/\s+/);
      const binary = tokens[0].toLowerCase();

      // Check against explicit blacklist
      if (this.blockedCommands.includes(binary)) {
        return {
          isSafe: false,
          reason: `Security Policy Violation: The command binary '${binary}' is blacklisted and restricted.`
        };
      }

      // 4. Malicious Path Traversal / Pattern Mitigation
      // Detect common destructive parameters or relative breakout strings ("../", "/etc", etc.)
      if (cleanSegment.includes('../') || cleanSegment.includes('..\\')) {
        return {
          isSafe: false,
          reason: "Security Policy Violation: Relative path traversal breakout attempts detected ('..')."
        };
      }

      // Root path containment scanning
      if (this.allowedPaths.length > 0) {
        const pathMatchesAllowed = this.allowedPaths.some(allowedPath => 
          cleanSegment.includes(allowedPath)
        );
        
        // If the command hints at file interaction but stays outside the perimeter workspace paths
        if ((cleanSegment.includes('/') || cleanSegment.includes('\\')) && !pathMatchesAllowed) {
          return {
            isSafe: false,
            reason: "Security Policy Violation: Action points to paths completely outside the designated sandbox perimeter workspace."
          };
        }
      }
    }
    // Create an internal network validator instance inside the engine check
    const networkGuard = new NetworkGatewayGuard();
    const networkCheck = networkGuard.validateRequest(trimmed);

    if (!networkCheck.isAllowed) {
      return {
        isSafe: false,
        reason: networkCheck.reason
      };
    }

    // If all internal assertions pass, mark as validated safely
    return {
      isSafe: true,
      sanitizedCommand: trimmed
    };
  }

  // Programmatic updates to the rules engine at runtime
  public blacklistCommand(cmd: string): void {
    if (!this.blockedCommands.includes(cmd.toLowerCase())) {
      this.blockedCommands.push(cmd.toLowerCase());
    }
  }
}
